name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-docker-image:latest .


      # Step 3: Build Docker image
      - name: Run Docker Image
        run: |
          docker run --name my-docker-container my-docker-image:latest
